name: ict4farmers
description: UNFE ict for farmers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: ../flutx
  objectbox: ^1.4.0
  objectbox_flutter_libs: any


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: 2.2.0
  path_provider: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

  
  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:


    #Map Styles
    - assets/map/


    #Profiles
    - assets/images/profile/


    #Shopping
    - assets/images/apps/shopping/
    - assets/images/apps/shopping/product/
    - assets/images/apps/shopping/offer/
    - assets/images/apps/shopping/camera/
    - assets/images/apps/shopping/vector/


    #Brand
    - assets/brand/

    #Hotel
    - assets/images/apps/hotel/

    #Places
    - assets/images/place/

    #Music
    - assets/images/apps/music/

    #Food
    - assets/images/apps/food/

    #estate
    - assets/images/apps/estate/

    #Course
    - assets/images/apps/course/

    #Chat
    - assets/images/apps/chat/

    #Social
    - assets/images/apps/social/

    #Other
    - assets/images/all/

    #Event
    - assets/images/apps/event/


    ###################---------------------- Custom Apps -------------------------#################

    ##Grocery
    - assets/images/apps/grocery/

    ##homemade
    - assets/images/apps/homemade/
    - assets/images/apps/homemade/products/
    - assets/images/apps/homemade/category/
    - assets/images/apps/homemade/shop/

    ##dating
    - assets/images/apps/dating/

    ##Muvi
    - assets/images/apps/muvi/

    ##CustomApps
    - assets/images/apps/cookify/
    - assets/images/apps/grocery/
    - assets/images/apps/medicare/

    ##Learning  (Material Design 3)
    - assets/images/apps/learning/images/
    - assets/images/apps/learning/icons/

    ##Cookify (Material Design 3)

    ##Estate (Material Design 3)

    ##Dating (Material Design 3)

    #Illustration
    - assets/illustration/food/
    - assets/illustration/shopping/
    - assets/illustration/hotel/
    - assets/illustration/music/

    #Month backgrounds
    - assets/images/month_background/

    #Languages
    - assets/lang/

    #Icons
    - assets/icons/

    #Other
    - assets/other/
    - assets/project/

    #main-branch