name: ict4farmers
description: UNFE ict for farmers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: ../flutx
  objectbox: ^1.4.0
  objectbox_flutter_libs: any
  connectivity_plus: ^2.2.0
  dio: ^4.0.4

  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: 2.2.0
  path_provider: ^2.0.9
  cached_network_image: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

  
  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:


    #Map Styles
    - assets/map/

    #Brand
    - assets/brand/

    #Languages
    - assets/lang/

    #Icons
    - assets/icons/

    #Other
    - assets/other/
    - assets/project/

    #main-branch